# Python :


In [ ]:
AnjaliSaini = "Student"   # ----> pascal case

anjaliSaini = "Student"   # ----> Camal case

anjali_saini = "Student"  # ----> Snake case

In [ ]:
x =  input("Enter the first number :")
y = input("Enter the second number :")
if x > y :
  print("x is the greater than y ")
else :
  print("y is the greater than x ")

print(f"value of x {x},value of y {y}")

Enter the first number :34
Enter the second number :41
y is the greater than x 
value of x 34,value of y 41


In [ ]:
z = input("Enter the Gender : ")
if z == "male" :
  print("Gender is male")
else  :
  print("Gender is female")



Enter the Gender : male
Gender is male


In [ ]:
w = int(input("Enter the number :"))
if w % 2 == 0 :
  print("the number is even :" , w )
else :
  print("the number is odd :" , w)

In [ ]:
t = int(input("Enter the name :"))
u = int(input("Enter the age : "))
if u > 18 :
  print("you are eligible to vote" , t)
else :
  print("you are not eligible to vote" , t )

In [ ]:
v = input("Enter the year :")
if (v % 4 == 0 ) && (v % 100 != 0) || (v % 400 == 0) :
  print("the year is leap year" , v)
else :
  print("the year is not leap year" , v)

In [ ]:
temp  = input("Enter the temperature : ")
if temp < 0 :
 print("Freezing cold ")
elif temp > 0 and temp < 10 :
 print("Very cold")
elif temp > 10 and temp < 20 :
 print("Cold")
elif temp > 20 and temp < 30 :
 print("Normal")
else :
  print("Hot")


In [1]:
import numpy as np

In [3]:
 arr1  = np.array([1,2,3,4,5,6,7,8,9,10])
 arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
l = [[1,2,3],[4,5,6]]
arr2 = np.array(l)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
n = np.arange(12)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
n1= n.reshape(3,4)
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
s1 = np.zeros(5)
s1

array([0., 0., 0., 0., 0.])

In [16]:
s2 = np.zeros([5,4])
s2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
s3 = np.zeros([2,4,5])
s3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [18]:
j1 = np.ones([3,4])
j1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
k1 = np.eye(4)
k1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
k2 = np.linspace(1,5,10)
k2

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
k3 = np.copy(k1)
k3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
k4 = np.empty(5)
k4

array([0., 0., 0., 0., 0.])

In [29]:
k5 = np.empty([5,5])
k5

array([[3.56388314e-315, 0.00000000e+000, 1.14428342e+243,
        8.03548366e-095, 7.18942963e+160],
       [1.89949265e-095, 1.19654332e+180, 4.63385214e+228,
        5.04431016e+180, 1.52553952e+247],
       [1.33907033e+199, 1.50093842e+247, 1.96925782e+243,
        9.44622326e+218, 5.04431016e+180],
       [1.52553952e+247, 5.76148218e+160, 5.42982163e+045,
        8.42959463e+252, 1.06505581e+094],
       [1.50093842e+247, 1.57430883e+161, 5.78027868e+074,
        5.50410564e-095, 3.82791391e-315]])

In [31]:
k6 = np.full(5,10)
k6

array([10, 10, 10, 10, 10])

In [33]:
k7 = np.full((2,5),10)
k7

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [36]:
f = np.arange(20)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
print(f[0:9])
print(f[5:12])
print(f[1:16:2])

[0 1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10 11]
[ 1  3  5  7  9 11 13 15]


In [41]:
f1 = np.arange(32).reshape(8,4)
f1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [50]:
print(f1[4,3])
print(f1[3][3])
print(f1[2:4])
print(f1[2:4,0:2])

19
15
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9]
 [12 13]]


In [55]:
w = np.arange(20)
w1 = np.where(w >15 , w*2 , w-w)
w1


array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 32,
       34, 36, 38])

In [57]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
print(np.shape(arr1))
print(np.shape(arr2))
result = arr1 + arr2
print(result)


(3,)
(2, 3)
[[2 4 6]
 [5 7 9]]


In [59]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10],[20]])
print(np.shape(arr1))
print(arr2)
print(np.shape(arr2))
result = arr1 + arr2
print(result)
#

(2, 3)
[[10]
 [20]]
(2, 1)
[[11 12 13]
 [24 25 26]]


In [61]:
a = np.arange(1,16).reshape(3,5)
print("original array :" , a)
print("\n Transpose of array :" , a.T)

original array : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 Transpose of array : [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [64]:
b = np.arange(8).reshape(2,4)
print(b)
print("\n Through rollaxis :")
print(np.rollaxis(b,1))


[[0 1 2 3]
 [4 5 6 7]]

 Through rollaxis :
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [67]:
b1 = np.rollaxis(b,1,1)
b1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
b2 = np.swapaxes(b,1,0)
b2

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [70]:
b3  = np.swapaxes(b,1,1)
b3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [77]:
x1 = np.arange(12).reshape(3,4)
x2 = np.arange(12).reshape(3,4)
print(x1)
print("\n",x2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [78]:
print(np.concatenate((x1,x2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [79]:
# Stack :
print(np.stack((x1,x2),0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [80]:
print(np.stack((x1,x2),1))

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]]


In [81]:
c = np.array([[1,2],[3,4]])
print(c)
d = np.array([[5,6],[7,8]])
print(d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [82]:
print(np.hstack((c,d)))

[[1 2 5 6]
 [3 4 7 8]]


In [83]:
print(np.vstack((c,d)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
# split :
a = np.arange(9)
print(a)
print(np.split(a,3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [85]:
print(np.split(a ,[4,7]))

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [86]:
a = np.arange(16).reshape(4,4)
print(a)
print("\n",np.hsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [87]:
 b = np.arange(16).reshape(4,4)
 print(b)
 print("\n",np.vsplit(b,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [88]:
# resize :
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.shape(a))

print("\n")
print(np.resize(a,(5,5)))
print(b)
print(np.shape(b))

[[1 2 3]
 [4 5 6]]
(2, 3)


[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]
 [4 5 6 1 2]
 [3 4 5 6 1]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


In [91]:
# unique :
a = np.array([11,22,3,3,22,11,4,5,6,78,11,89])
print(a)
print(np.unique(a))

[11 22  3  3 22 11  4  5  6 78 11 89]
[ 3  4  5  6 11 22 78 89]


In [92]:
y1 = np.random.rand()
y2 = np.random.rand(10)
y3 = np.random.rand(2,5)
print(y1)
print(y2)
print(y3)

0.141797072305878
[0.23692231 0.83517089 0.58603309 0.55860862 0.0544265  0.4031375
 0.4600265  0.18686156 0.98716848 0.14774178]
[[0.71923972 0.72922665 0.36145586 0.63761829 0.61523909]
 [0.05782403 0.07823544 0.74488746 0.12634295 0.27173598]]


In [93]:
z1 = np.random.randn()
z2 = np.random.randn(5)
z3 = np.random.randn(2,5)
print(z1)
print(z2)
print(z3)

-2.230132195940118
[ 0.22055857 -1.53719022  0.53020334  0.97650132  0.57377287]
[[-0.95126005 -1.15989396  0.367406    0.91217473 -0.06173367]
 [-0.62514699  1.26472287 -1.60409842  1.11667997  0.03877697]]


In [94]:
q1 = np.random.randint(10)
q2 = np.random.randint(10,20)
q3 = np.random.randint(10,20,5)
print(q1)
print(q2)
print(q3)

2
16
[18 14 16 14 18]


In [96]:
e = np.array([1,2,3,4,5,6,7])
e1 = np.random.shuffle(e)
print(e1)
print(e)

None
[5 3 4 7 1 2 6]


In [97]:
data = np.random.permutation(e)
print(data)
print(e)

[5 3 4 2 1 7 6]
[5 3 4 7 1 2 6]
